#!/usr/bin/env python
"""Reverse-fall swing-up generation: explore the predecessors of upright.

IDEA (user): the swing-up must arrive at upright through some family of bent
"predecessor" shapes; fix/enumerate those instead of hoping the NLP finds them.

IMPLEMENTATION: the chain dynamics are TIME-REVERSIBLE (theta-EOM is even in
thetad; thetadd invariant under t -> -t). So: start AT upright perturbed along a
chosen mixture of unstable directions (the arrival-shape family), let the chain
FALL, brake it with an energy-shaping + hang-LQR policy so it lands at the hang
at rest, record (theta, thetad, a, v), and TIME-REVERSE the record
(thetad -> -thetad, v -> -v, controls mirrored). The result is an EXACT swing-up
solution of the ODE at the integration step:
  - terminal approach shape = the chosen fall-departure direction (the knob),
  - zero collocation/interpolation defect (generated by the same RK4 + ZOH the
    simulator uses, at the same dt),
  - no settle band: the nominal leaves upright at the natural unstable rate, so
    reversed it spends the minimum possible time near-straight.
Then test full-state TVLQR trackability as usual.

Run:  uv run python repro/reverse_fall.py N [n_workers] [--dt DT]
"""
import sys, os, pathlib, time
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import numpy as np
import warnings; warnings.filterwarnings("ignore")
import multiprocessing as mp
from scipy.linalg import solve_continuous_are, expm

from pendulum.dynamics import Chain
from pendulum.sim import rk4_step
from repro.optimize_n6 import build_tvlqr
from repro.generate_n6 import bend_excite_np

G = 9.81
N = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else 6
A_MAX, V_MAX = 25.0, 14.0
T_FALL = 90.0                  # max fall duration before giving up
BRAKE_CAP = 4.0                # gentle brake settles ~2x faster than saturated
SETTLE_TH, SETTLE_TD = 0.03, 0.02   # hang-landing tolerance (rad, rad/s)
POOL = pathlib.Path(f"repro/pool_revfall_n{N}")

_t0 = time.monotonic()
def log(m): print(f"[{time.monotonic()-_t0:7.1f}s] {m}", flush=True)


# ---- upright linearization: unstable directions = the arrival-shape family ----
def unstable_directions(chain):
    """Eigen-decomposition of the upright [theta,thetad] linearization (a=0).
    Returns (n, 2n) array: each row an unstable eigenvector (real), sorted by
    eigenvalue (fastest first)."""
    n = chain.n
    Ac = np.zeros((2 * n, 2 * n))
    Ac[:n, n:] = np.eye(n)
    Ac[n:, :n] = chain._M0inv @ (G * np.diag(chain.b))
    w, V = np.linalg.eig(Ac)
    idx = [i for i in range(2 * n) if w[i].real > 1e-6 and abs(w[i].imag) < 1e-9]
    idx.sort(key=lambda i: -w[i].real)
    dirs = np.real(V[:, idx]).T
    return dirs / np.linalg.norm(dirs, axis=1, keepdims=True), np.real(w[idx])


def hang_lqr(chain):
    """LQR about the hang (theta=pi), state [theta-pi, thetad, v], input a."""
    n = chain.n
    Mh = chain.mass_matrix(np.full(n, np.pi))
    Mhi = np.linalg.inv(Mh)
    Ac = np.zeros((2 * n + 1, 2 * n + 1))
    Ac[:n, n:2 * n] = np.eye(n)
    Ac[n:2 * n, :n] = Mhi @ (-G * np.diag(chain.b))     # sin(pi+e) = -e
    Bc = np.zeros((2 * n + 1, 1))
    Bc[n:2 * n, 0] = Mhi @ chain.b                       # cos(pi) = -1, -a*b*cos = +a*b
    Bc[2 * n, 0] = 1.0
    Q = np.diag([20.0] * n + [2.0] * n + [0.5]); R = np.array([[1.0]])
    P = solve_continuous_are(Ac, Bc, Q, R)
    return (np.linalg.solve(R, Bc.T @ P)).ravel()


def fall_policy(chain, Kh):
    """Returns a(theta, thetad, v): energy-shaping brake + hang-LQR blend."""
    n = chain.n
    b = chain.b
    E_hang = -G * np.sum(b)
    def pol(th, td, v):
        M = chain.mass_matrix(th)
        E = 0.5 * td @ M @ td + G * np.sum(b * np.cos(th))
        S = float(np.sum(b * np.cos(th) * td))
        dE = E - E_hang
        a = BRAKE_CAP * np.tanh(0.6 * S * dE)             # gentle dissipation
        # blend in the hang LQR when close (kills residual swing, lands at rest)
        err = np.concatenate([(th - np.pi + np.pi) % (2 * np.pi) - np.pi, td, [v]])
        wgt = np.exp(-((np.abs(err[:n]).max() / 0.6) ** 2))
        a = (1 - wgt) * a - wgt * float(Kh @ err)
        a -= 0.3 * v                                      # keep pivot velocity bounded
        return float(np.clip(a, -A_MAX, A_MAX))
    return pol


def gen_fall(task):
    """One fall: (tag, mix weights over unstable dirs, eps, dt). Integrate the
    braked fall from upright+eps*dir; if it lands at the hang within bounds,
    time-reverse and save."""
    os.environ["OMP_NUM_THREADS"] = "1"
    tag, mix, eps, dt = task
    chain = Chain(N, G)
    dirs, lams = unstable_directions(chain)
    Kh = hang_lqr(chain)
    pol = fall_policy(chain, Kh)
    d0 = mix @ dirs; d0 /= np.linalg.norm(d0)
    y = np.concatenate([np.zeros(N), np.zeros(N)]) + eps * d0
    v = 0.0
    TH, TD, AA, VV = [], [], [], []
    ok = False
    for k in range(int(T_FALL / dt)):
        a = pol(y[:N], y[N:], v)
        TH.append(y[:N].copy()); TD.append(y[N:].copy()); AA.append(a); VV.append(v)
        y = rk4_step(chain, y, a, dt); v += a * dt
        if abs(v) > V_MAX or not np.isfinite(y).all():
            return (tag, None, "v/nan")
        herr = np.abs((y[:N] - np.pi + np.pi) % (2 * np.pi) - np.pi)
        if herr.max() < SETTLE_TH and np.abs(y[N:]).max() < SETTLE_TD and abs(v) < 0.05:
            ok = True
            TH.append(y[:N].copy()); TD.append(y[N:].copy()); AA.append(0.0); VV.append(v)
            break
    if not ok:
        return (tag, None, "no-settle")
    TH = np.array(TH); TD = np.array(TD); AA = np.array(AA); VV = np.array(VV)
    # time-reverse: state at sample k becomes state at K-k; rates/velocity negate.
    # Controls: a applied on [t_k, t_k+dt) forward maps to [T-t_k-dt, T-t_k)
    # reversed, i.e. reversed ZOH sequence shifts by one: a_rev[k] = a[K-1-k].
    THr = TH[::-1].copy(); TDr = -TD[::-1].copy(); VVr = -VV[::-1].copy()
    Ar = AA[:-1][::-1].copy()
    Ar = np.append(Ar, 0.0)
    t = np.arange(len(THr)) * dt
    cmin = float(min(bend_excite_np(chain, THr[i]) for i in range(0, len(t), 10)))
    fn = POOL / f"{tag}.npz"
    np.savez(fn, t=t, theta=THr, thetad=TDr, a=Ar, v=VVr, T=t[-1], dt=dt,
             cmin=cmin, mix=mix, eps=eps)
    return (tag, str(fn), f"T={t[-1]:.1f}s cmin={cmin:.2f}")


def eval_track(item):
    """Full-state TVLQR at the GENERATION dt (node-exact, zero-defect nominal)."""
    os.environ["OMP_NUM_THREADS"] = "1"
    tag, fn = item
    d = dict(np.load(fn))
    chain = Chain(N, G); dt = float(d["dt"])
    th, td, a_ff, v_nom = d["theta"], d["thetad"], d["a"], d["v"]
    Q = np.diag([50.0] * N + [5.0] * N + [1.0]); R = np.array([[0.1]])
    QF = np.diag([2000.0] * N + [200.0] * N + [10.0])
    Ks = build_tvlqr(chain, th, td, a_ff, dt, Q, R, QF)
    y = np.concatenate([th[0], td[0]]); v = v_nom[0]; maxK = 0.0
    for k in range(len(Ks)):
        z = np.concatenate([y[:N], y[N:], [v]]); zn = np.concatenate([th[k], td[k], [v_nom[k]]])
        a = a_ff[k] - float((Ks[k] @ (z - zn))[0]); maxK = max(maxK, float(np.abs(Ks[k]).max()))
        y = rk4_step(chain, y, a, dt); v += a * dt
        if not np.isfinite(y).all():
            return dict(tag=tag, ok=False, final=np.inf, maxK=maxK, cmin=float(d["cmin"]))
    final = float(np.max(np.abs((y[:N] + np.pi) % (2 * np.pi) - np.pi)))
    return dict(tag=tag, ok=final < 0.05, final=final, maxK=maxK, cmin=float(d["cmin"]))


def main():
    global POOL
    nw = int(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2].isdigit() else min(40, mp.cpu_count() - 4)
    dt = float(sys.argv[sys.argv.index("--dt") + 1]) if "--dt" in sys.argv else 0.004
    POOL = pathlib.Path(f"repro/pool_revfall_n{N}/dt{dt:g}")   # per-dt (runs don't clobber)
    POOL.mkdir(parents=True, exist_ok=True)
    for p in POOL.glob("*.npz"):
        p.unlink()
    chain = Chain(N, G)
    dirs, lams = unstable_directions(chain)
    log(f"N={N}: {len(lams)} unstable modes, lambda = {np.round(lams, 2)}")

    # arrival-shape family: single modes (+/-), pairwise mixtures, random mixtures
    tasks = []
    for i in range(len(lams)):
        for sgn in (1.0, -1.0):
            m = np.zeros(len(lams)); m[i] = sgn
            tasks.append((f"mode{i}{'p' if sgn > 0 else 'm'}", m, 1e-3, dt))
    rng = np.random.default_rng(0)
    if "--slow4" in sys.argv:
        # mixtures restricted to the 4 SLOWEST unstable modes (the trackable
        # arrival family at N=6 was slow-mode-dominated)
        for j in range(32):
            m = np.zeros(len(lams)); m[-4:] = rng.normal(size=4)
            tasks.append((f"slow{j}", m, 1e-3, dt))
    else:
        for j in range(24):
            m = rng.normal(size=len(lams))
            tasks.append((f"mix{j}", m, 1e-3, dt))
    log(f"generating {len(tasks)} braked falls (dt={dt}) on {nw} workers...")
    with mp.Pool(nw) as pool:
        gen = pool.map(gen_fall, tasks)
    landed = [(tg, fn) for tg, fn, msg in gen if fn]
    for tg, fn, msg in gen:
        log(f"  {tg:10s} {'LANDED ' + msg if fn else 'fail: ' + msg}")
    log(f"{len(landed)}/{len(tasks)} falls landed at the hang")
    if not landed:
        return

    log("evaluating reversed trajectories (full-state TVLQR, node-exact)...")
    with mp.Pool(nw) as pool:
        evals = pool.map(eval_track, landed)
    evals.sort(key=lambda e: (not e["ok"], e["final"]))
    for e in evals:
        log(f"  {e['tag']:10s} ok={e['ok']!s:5s} final={np.degrees(e['final']):8.3f}deg "
            f"cmin={e['cmin']:.3f} maxK={e['maxK']:.0f}")
    wins = [e for e in evals if e["ok"]]
    log(f"TRACKABLE: {len(wins)}/{len(evals)}" + (f" best={wins[0]['tag']}" if wins else ""))


if __name__ == "__main__":
    main()
